name: "Build latest images & releases"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  Check-version:
    runs-on: ubuntu-latest
    name: "Check version & Delete release"
    outputs:
      latest_now: ${{ steps.get-version.outputs.latest_now }}
      latest_new: ${{ steps.get-version.outputs.latest_new }}
      latest_renew: ${{ steps.get-version.outputs.latest_renew }}
      commit: ${{ steps.get-version.outputs.commit }}
      go_version: ${{ steps.get-version.outputs.go_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Check version
        id: get-version
        run: |
          LATEST_NOW=$(awk '/latest/{print $NF; exit}' README.md)

          LATEST_NEW=$(curl -s 'https://api.github.com/repos/XTLS/Xray-core/releases' | jq -r '.[0].tag_name')

          echo "LATEST_NOW: $LATEST_NOW"
          echo "LATEST_NEW: $LATEST_NEW"

          if [ "$LATEST_NOW" != "$LATEST_NEW" ]; then
            LATEST_RENEW=1
          fi

          if [ "$LATEST_NOW" != "$LATEST_NEW" ]; then
            echo "latest_now=$LATEST_NOW" >> $GITHUB_OUTPUT
            echo "latest_new=$LATEST_NEW" >> $GITHUB_OUTPUT
            echo "latest_renew=$LATEST_RENEW" >> $GITHUB_OUTPUT
          fi

          DATE=$(date "+%Y/%m/%d")
          if [ "$LATEST_RENEW" == '1' ]; then
            COMMIT="Build to $LATEST_NEW by Github Actions, $DATE"
            echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          fi
  # =============================================================================================================================================================================================
  Build-latest-image:
    needs: Check-version
    runs-on: ubuntu-latest
    name: "Build latest image"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
      LATEST_NEW: ${{ needs.Check-version.outputs.latest_new }}

    steps:
      - name: Checkout code
        if: ${{ env.LATEST_NEW != '' }}
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if: ${{ env.LATEST_NEW != '' }}
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        if: ${{ env.LATEST_NEW != '' }}
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        if: ${{ env.LATEST_NEW != '' }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        if: ${{ env.LATEST_NEW != '' }}
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/i386, linux/amd64, linux/arm/v7, linux/arm64
          build-args: BRANCH=${{ env.LATEST_NEW }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.LATEST_NEW }}
  # =============================================================================================================================================================================================
  Mark-image-version:
    needs:
      - Check-version
      - Build-latest-image
    runs-on: ubuntu-latest
    name: "Mark the image version"
    env:
      LATEST_NOW: ${{ needs.Check-version.outputs.latest_now }}
      LATEST_NEW: ${{ needs.Check-version.outputs.latest_new }}
      LATEST_RENEW: ${{ needs.Check-version.outputs.latest_renew }}
      COMMIT: ${{ needs.Check-version.outputs.commit }}

    steps:
      - name: checkout
        if: ${{ env.COMMIT != '' }}
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Check and Mark
        if: ${{ env.COMMIT != '' }}
        run: |
          if [ "${{ env.LATEST_RENEW }}" == '1' ]; then
            sed -i "s/\(latest.*:\).*/\1 ${{ env.LATEST_NEW }}/" README.md
          fi

          git checkout --orphan tmp_work
          git branch -d main

      - name: Upload to repository
        if: ${{ env.COMMIT != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: ${{ env.COMMIT }}
          create_branch: true
          branch: main
          push_options: --force

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "cancelled, skipped, success"
